name: 'test-post-if-condition'
description: ''
inputs:
  name:
    description: 'Your name'
    required: true
  always-save:
    description: 'Set to true to always save'
    required: true
    default: false
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: success() || (inputs.always-save == 'true' && always())
