name: 'test-post-if-condition'
description: ''
inputs:
  always-run-post:
    description: 'Always run the post step'
    required: true
    default: false
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: success() || (inputs.always-run-post == 'true' && always())
