name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test passing
        uses: ./
        with:
          name: OK
      - name: Test passing with always save
        uses: ./
        with:
          name: OK
          always-save: true
      - name: Test failure with always save
        uses: ./
        with:
          name: fail
          always-save: true

